// =========================================================
// IRIDESCENCE EFFECT — GLSL
// =========================================================
// Replaces the specular highlight's hue with a palette sampled from a
// LUT while preserving its luminance. The hue this pixel lands on is
// driven by iriT — a STATIC (no-time) field that combines:
//   - NdotL (cursor angle relative to surface normal) — the
//     dominant term, so moving the cursor shifts the apparent
//     palette index across the highlight.
//   - fbm noise of texUV — gives spatial variation so different
//     areas read as different colours at the same cursor position.
//   - cursor blob bump — pushes iriT further when the blob is over
//     a region.
//
// PALETTE ENGINE (changed in v20):
//   Previously: `a + b*cos(2*pi*(c*t + u_iriPhase))` — a cosine palette
//   with a fixed Pearl basis. Single hue knob just rotated it.
//
//   Now: `texture2D(u_iriLUT, vec2(fract(t + u_iriHueShift), 0.5))`.
//   The LUT is generated by JS — from the Pearl cosine formula in
//   "Pearl" mode, or from user-defined gradient stops in "Custom"
//   mode. Hue is still a uniform applied at sample time so dragging
//   the hue slider doesn't trigger LUT regeneration.
//
// Function signatures are unchanged so external callers
// (Bloom's halo tint, particles' hue shift, solid's blob iri bump)
// keep working without modification.
//
// Host material contract (unchanged):
//   - declare `vec3 specular` (Fresnel-coloured) before EFFECTS_APPLY
//   - declare `vec3 halo = vec3(0.0)` and `float haloMask` in haloBlock
//   - `iriT` — surface field for the palette lookup
//   - `flow` — time-drifting field (used by Bloom's halo)
//
export const uniforms = /* glsl */ `
  uniform sampler2D u_iriLUT;
  uniform float u_iriHueShift;
  uniform float u_iriIntensity;
`;

export const helpers = /* glsl */ `
  // LUT-backed palette. WrapS=Repeat on the texture handles t values
  // outside [0,1) but fract() makes the hue rotation predictable.
  vec3 iridescencePalette(float t){
    float u = fract(t + u_iriHueShift);
    return texture2D(u_iriLUT, vec2(u, 0.5)).rgb;
  }

  // Multiplicative tint — used by Bloom for the halo. Returns
  // vec3(1.0) at intensity=0 so multiplying is a no-op.
  vec3 iridescence(float t){
    float k = clamp(u_iriIntensity, 0.0, 2.0);
    vec3 palette = iridescencePalette(t);
    return mix(vec3(1.0), palette, min(k, 1.0));
  }

  // Replace the spec's hue with the palette while preserving its
  // luminance. At intensity=0 the spec is unchanged; at intensity=1
  // the spec's hue is fully palette (same brightness); at intensity=2
  // the spec is palette AND boosted brightness for HDR push.
  vec3 tintSpecular(vec3 spec, float t){
    float k = clamp(u_iriIntensity, 0.0, 2.0);
    if (k < 0.001) return spec;
    vec3 palette = iridescencePalette(t);
    float lum = dot(spec, vec3(0.2126, 0.7152, 0.0722));
    vec3 tinted = palette * lum * 1.6;
    vec3 base = mix(spec, tinted, min(k, 1.0));
    float overdrive = max(k - 1.0, 0.0);
    return base * (1.0 + overdrive * 1.5);
  }
`;

// Apply: tint the spec ONLY. No halo write — that's Bloom's job.
//
export const apply = /* glsl */ `
    if (u_iriIntensity > 0.001) {
      specular = tintSpecular(specular, iriT);
    }
`;
